module.exports = {
    brunncard: require("./brunncard"),
    checkout: require("./checkout"),
    datenschutzerklaerung: require("./datenschutzerklaerung"),
    flughafen_transfer_moedling_austria: require("./flughafen_transfer_moedling_austria"),
    home: require("./home"),
    impressum: require("./impressum"),
    kontakt: require("./kontakt"),
    laxenburg_karte: require("./laxenburg_karte"),
    laxenburgkarte: require("./laxenburgkarte"),
    login: require("./login"),
    online_taxi_bestellen: require("./online_taxi_bestellen"),
    preise: require("./preise"),
    register: require("./register"),
    taxi_flotte: require("./taxi_flotte"),
    unser_service: require("./unser_service"),
    vom_flughafen: require("./vom_flughafen"),
    wiener_neudorf_card: require("./wiener_neudorf_card"),
    zum_flughafen: require("./zum_flughafen"),
    admin: require("./admin"),
    profile: require("./profile")
};